version: '3'

services:
  app:
    image: golang:1.21
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - GOCACHE=/app/.cache/data
      - GOMODCACHE=/app/.cache/mod
    env_file:
      - .secrets.env
    command: go run /app/cmd/link_resolution
